spring.application.name=prj_banhcay

# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/banhcay
spring.datasource.username=postgres
spring.datasource.password=382004
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate / JPA
# update: Tự động tạo bảng hoặc cập nhật cấu hình bảng dựa trên Entity Java (như class Account của bạn)
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL xuống console để bạn dễ debug khi gọi API
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Định dạng ngôn ngữ SQL chuẩn cho PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.ai.google.genai.api-key=${GCP_API_KEY}